openapi: 3.0.3
info:
  title: Divider Service
  description: An example illustrating error handling in goa. See docs/ErrorHandling.md.
  version: "1.0"
servers:
- url: localhost:80
  description: Default server for divider
paths:
  /div/{a}/{b}:
    get:
      tags:
      - divider
      summary: divide divider
      operationId: divider#divide
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        schema:
          type: number
          description: Left operand
          example: 0.789075649868927
          format: double
        example: 0.5111166900916506
      - name: b
        in: path
        description: Right operand
        required: true
        schema:
          type: number
          description: Right operand
          example: 0.7057874505310562
          format: double
        example: 0.39685847459472906
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: number
                example: 0.6217568753915087
                format: double
              example: 0.16566737152718328
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
        "504":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
  /idiv/{a}/{b}:
    get:
      tags:
      - divider
      summary: integer_divide divider
      operationId: divider#integer_divide
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        schema:
          type: integer
          description: Left operand
          example: 393318831510271335
          format: int64
        example: 5453550585455534152
      - name: b
        in: path
        description: Right operand
        required: true
        schema:
          type: integer
          description: Right operand
          example: 3216794369390999806
          format: int64
        example: 7239368640568786456
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: integer
                example: 6378977159087295045
                format: int64
              example: 7945609215329634748
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
        "417":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
        "504":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
components:
  schemas:
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: true
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: false
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: false
      description: integer division has remainder
      example:
        fault: false
        id: 123abc
        message: parameter 'p' must be an integer
        name: bad_request
        temporary: false
        timeout: true
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
