openapi: 3.0.3
info:
  title: File Upload Service
  description: HTTP service for uploading files using the tus protocol (https://tus.io)
  version: "1.0"
servers:
- url: http://localhost:8000/upload
  description: Upload hosts the upload service.
paths:
  /upload:
    options:
      tags:
      - tus
      summary: options tus
      description: Clients use the OPTIONS method to gather information about the Serverâ€™s current configuration.
      operationId: tus#options
      responses:
        "204":
          description: ""
          headers:
            Tus-Checksum-Algorithm:
              description: A Client MAY include the Upload-Checksum header in a PATCH request. Once the entire request has been received, the Server MUST verify the uploaded chunk against the provided checksum using the specified algorithm.
              required: true
              schema:
                type: string
                description: A Client MAY include the Upload-Checksum header in a PATCH request. Once the entire request has been received, the Server MUST verify the uploaded chunk against the provided checksum using the specified algorithm.
                example: md5,sha1,crc32
                enum:
                - md5,sha1,crc32
              example: md5,sha1,crc32
            Tus-Extension:
              description: tusExtension is a comma separated list of extensions supported by the server. This implementation supports the creation, creation-with-upload, expiration, checksum and termination extensions
              required: true
              schema:
                type: string
                description: tusExtension is a comma separated list of extensions supported by the server. This implementation supports the creation, creation-with-upload, expiration, checksum and termination extensions
                example: creation,creation-with-upload,creation-defer-length,expiration,checksum,termination
                enum:
                - creation,creation-with-upload,creation-defer-length,expiration,checksum,termination
              example: creation,creation-with-upload,creation-defer-length,expiration,checksum,termination
            Tus-Max-Size:
              description: tusMaxSize represents the maximum allowed size of an entire upload in bytes.
              schema:
                type: integer
                description: tusMaxSize represents the maximum allowed size of an entire upload in bytes.
                example: 8826818837706880
                format: int64
              example: 7763914550509985284
            Tus-Resumable:
              description: tusResumable represents a tus protocol version.
              required: true
              schema:
                type: string
                description: tusResumable represents a tus protocol version.
                example: 1.0.0
                pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$
              example: 1.0.0
            Tus-Version:
              description: tusVersion is a comma separated list of protocol versions supported by the server. This implementation only supports 1.0.0.
              required: true
              schema:
                type: string
                description: tusVersion is a comma separated list of protocol versions supported by the server. This implementation only supports 1.0.0.
                example: 1.0.0
                enum:
                - 1.0.0
              example: 1.0.0
          content:
            application/json:
              example: {}
        "412":
          description: ""
          headers:
            Tus-Version:
              description: Comma separated list of supported versions.
              required: true
              schema:
                type: string
                description: Comma separated list of supported versions.
                example: 1.0.0
                enum:
                - 1.0.0
              example: 1.0.0
          content:
            application/json:
              example: {}
    post:
      tags:
      - tus
      summary: post tus
      description: Clients use the POST method against a known upload creation URL to request a new upload resource.
      operationId: tus#post
      parameters:
      - name: Tus-Resumable
        in: header
        description: tusResumable represents a tus protocol version.
        allowEmptyValue: true
        required: true
        schema:
          type: string
          description: tusResumable represents a tus protocol version.
          example: 1.0.0
          pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$
        example: 1.0.0
      - name: Upload-Length
        in: header
        description: uploadLength represents the size of the entire upload in bytes.
        allowEmptyValue: true
        schema:
          type: integer
          description: uploadLength represents the size of the entire upload in bytes.
          example: 479317460011377657
          format: int64
        example: 7585706898538598738
      - name: Upload-Defer-Length
        in: header
        description: The Upload-Defer-Length request and response header indicates that the size of the upload is not known currently and will be transferred later.
        allowEmptyValue: true
        schema:
          type: integer
          description: The Upload-Defer-Length request and response header indicates that the size of the upload is not known currently and will be transferred later.
          example: 1
          enum:
          - 1
        example: 1
      - name: Upload-Checksum
        in: header
        description: A Client MAY include the Upload-Checksum header in a PATCH request. Once the entire request has been received, the Server MUST verify the uploaded chunk against the provided checksum using the specified algorithm.
        allowEmptyValue: true
        schema:
          type: string
          description: A Client MAY include the Upload-Checksum header in a PATCH request. Once the entire request has been received, the Server MUST verify the uploaded chunk against the provided checksum using the specified algorithm.
          example: sha1 Kq5sNclPz7QV2+lfQIuc6R7oRu0=
        example: sha1 Kq5sNclPz7QV2+lfQIuc6R7oRu0=
      - name: Upload-Metadata
        in: header
        description: The Client MAY supply the Upload-Metadata header to add additional metadata to the upload creation request.
        allowEmptyValue: true
        schema:
          type: string
          description: The Client MAY supply the Upload-Metadata header to add additional metadata to the upload creation request.
          example: key1 val1,key2 val2
        example: key1 val1,key2 val2
      - name: Tus-Max-Size
        in: header
        description: Length of the upload
        allowEmptyValue: true
        schema:
          type: integer
          description: Length of the upload
          example: 372598282905132216
          format: int64
        example: 477506491488379127
      responses:
        "201":
          description: ""
          headers:
            Location:
              description: URL of created resource
              required: true
              schema:
                type: string
                description: URL of created resource
                example: /files/123
                format: uri
              example: /files/123
            Tus-Resumable:
              description: tusResumable represents a tus protocol version.
              required: true
              schema:
                type: string
                description: tusResumable represents a tus protocol version.
                example: 1.0.0
                pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$
              example: 1.0.0
            Upload-Expires:
              description: The Upload-Expires response header indicates the time after which the unfinished upload expires.
              schema:
                type: string
                description: The Upload-Expires response header indicates the time after which the unfinished upload expires.
                example: Wed, 25 Jun 2014 16:00:00 GMT
              example: Wed, 25 Jun 2014 16:00:00 GMT
            Upload-Offset:
              description: uploadOffset represents a byte offset within a resource.
              required: true
              schema:
                type: integer
                description: uploadOffset represents a byte offset within a resource.
                example: 4112570914862829890
                format: int64
              example: 7138406606232779808
          content:
            application/json:
              example: {}
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
        "412":
          description: ""
          headers:
            Tus-Version:
              description: Comma separated list of supported versions.
              required: true
              schema:
                type: string
                description: Comma separated list of supported versions.
                example: 1.0.0
                enum:
                - 1.0.0
              example: 1.0.0
          content:
            application/json:
              example: {}
        "413":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
        "460":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
  /upload/{id}:
    delete:
      tags:
      - tus
      summary: delete tus
      description: Clients use the DELETE method to terminate completed and unfinished uploads allowing the Server to free up used resources.
      operationId: tus#delete
      parameters:
      - name: id
        in: path
        description: 'IDs are generated using Xid: https://github.com/rs/xid'
        required: true
        schema:
          type: string
          description: 'IDs are generated using Xid: https://github.com/rs/xid'
          example: nksl3lk0upnkabff2l6l
          pattern: '[0-9a-v]{20}'
        example: shnkqp7ovukfd7so0gqe
      - name: Tus-Resumable
        in: header
        description: tusResumable represents a tus protocol version.
        allowEmptyValue: true
        required: true
        schema:
          type: string
          description: tusResumable represents a tus protocol version.
          example: 1.0.0
          pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$
        example: 1.0.0
      responses:
        "204":
          description: ""
          headers:
            Tus-Resumable:
              description: tusResumable represents a tus protocol version.
              required: true
              schema:
                type: string
                description: tusResumable represents a tus protocol version.
                example: 1.0.0
                pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$
              example: 1.0.0
          content:
            application/json:
              example: {}
        "404":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
        "410":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
        "412":
          description: ""
          headers:
            Tus-Version:
              description: Comma separated list of supported versions.
              required: true
              schema:
                type: string
                description: Comma separated list of supported versions.
                example: 1.0.0
                enum:
                - 1.0.0
              example: 1.0.0
          content:
            application/json:
              example: {}
    head:
      tags:
      - tus
      summary: head tus
      description: Clients use the HEAD request to determine the offset at which the upload should be continued.
      operationId: tus#head
      parameters:
      - name: id
        in: path
        description: 'IDs are generated using Xid: https://github.com/rs/xid'
        required: true
        schema:
          type: string
          description: 'IDs are generated using Xid: https://github.com/rs/xid'
          example: vvhtoopfg74h629078jr
          pattern: '[0-9a-v]{20}'
        example: 9dagbu3th4v7g0fjbjhe
      - name: Tus-Resumable
        in: header
        description: tusResumable represents a tus protocol version.
        allowEmptyValue: true
        required: true
        schema:
          type: string
          description: tusResumable represents a tus protocol version.
          example: 1.0.0
          pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$
        example: 1.0.0
      responses:
        "200":
          description: ""
          headers:
            Tus-Resumable:
              description: tusResumable represents a tus protocol version.
              required: true
              schema:
                type: string
                description: tusResumable represents a tus protocol version.
                example: 1.0.0
                pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$
              example: 1.0.0
            Upload-Defer-Length:
              description: The Upload-Defer-Length request and response header indicates that the size of the upload is not known currently and will be transferred later.
              schema:
                type: integer
                description: The Upload-Defer-Length request and response header indicates that the size of the upload is not known currently and will be transferred later.
                example: 1
                enum:
                - 1
              example: 1
            Upload-Length:
              description: uploadLength represents the size of the entire upload in bytes.
              schema:
                type: integer
                description: uploadLength represents the size of the entire upload in bytes.
                example: 518079758982137479
                format: int64
              example: 4999229605321017948
            Upload-Metadata:
              description: The Client MAY supply the Upload-Metadata header to add additional metadata to the upload creation request.
              schema:
                type: string
                description: The Client MAY supply the Upload-Metadata header to add additional metadata to the upload creation request.
                example: key1 val1,key2 val2
              example: key1 val1,key2 val2
            Upload-Offset:
              description: uploadOffset represents a byte offset within a resource.
              required: true
              schema:
                type: integer
                description: uploadOffset represents a byte offset within a resource.
                example: 5028804486247352317
                format: int64
              example: 3304173154312827797
          content:
            application/json:
              example: {}
        "404":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
        "410":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
        "412":
          description: ""
          headers:
            Tus-Version:
              description: Comma separated list of supported versions.
              required: true
              schema:
                type: string
                description: Comma separated list of supported versions.
                example: 1.0.0
                enum:
                - 1.0.0
              example: 1.0.0
          content:
            application/json:
              example: {}
    patch:
      tags:
      - tus
      summary: patch tus
      description: Clients use the PATCH method to start or resume an upload.
      operationId: tus#patch
      parameters:
      - name: id
        in: path
        description: 'IDs are generated using Xid: https://github.com/rs/xid'
        required: true
        schema:
          type: string
          description: 'IDs are generated using Xid: https://github.com/rs/xid'
          example: nnub7u7nkmlsfsc6ses6
          pattern: '[0-9a-v]{20}'
        example: 07aard2338glhm8vt8oo
      - name: Tus-Resumable
        in: header
        description: tusResumable represents a tus protocol version.
        allowEmptyValue: true
        required: true
        schema:
          type: string
          description: tusResumable represents a tus protocol version.
          example: 1.0.0
          pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$
        example: 1.0.0
      - name: Upload-Offset
        in: header
        description: uploadOffset represents a byte offset within a resource.
        allowEmptyValue: true
        required: true
        schema:
          type: integer
          description: uploadOffset represents a byte offset within a resource.
          example: 6785548980349758944
          format: int64
        example: 8533053218528786631
      - name: Upload-Checksum
        in: header
        description: A Client MAY include the Upload-Checksum header in a PATCH request. Once the entire request has been received, the Server MUST verify the uploaded chunk against the provided checksum using the specified algorithm.
        allowEmptyValue: true
        schema:
          type: string
          description: A Client MAY include the Upload-Checksum header in a PATCH request. Once the entire request has been received, the Server MUST verify the uploaded chunk against the provided checksum using the specified algorithm.
          example: sha1 Kq5sNclPz7QV2+lfQIuc6R7oRu0=
        example: sha1 Kq5sNclPz7QV2+lfQIuc6R7oRu0=
      responses:
        "204":
          description: ""
          headers:
            Tus-Resumable:
              description: tusResumable represents a tus protocol version.
              required: true
              schema:
                type: string
                description: tusResumable represents a tus protocol version.
                example: 1.0.0
                pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$
              example: 1.0.0
            Upload-Expires:
              description: The Upload-Expires response header indicates the time after which the unfinished upload expires.
              schema:
                type: string
                description: The Upload-Expires response header indicates the time after which the unfinished upload expires.
                example: Wed, 25 Jun 2014 16:00:00 GMT
              example: Wed, 25 Jun 2014 16:00:00 GMT
            Upload-Offset:
              description: uploadOffset represents a byte offset within a resource.
              required: true
              schema:
                type: integer
                description: uploadOffset represents a byte offset within a resource.
                example: 6674965573629583913
                format: int64
              example: 423322217614941725
          content:
            application/json:
              example: {}
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
        "404":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
        "409":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
        "410":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
        "412":
          description: ""
          headers:
            Tus-Version:
              description: Comma separated list of supported versions.
              required: true
              schema:
                type: string
                description: Comma separated list of supported versions.
                example: 1.0.0
                enum:
                - 1.0.0
              example: 1.0.0
          content:
            application/json:
              example: {}
        "415":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
        "460":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
components:
  schemas:
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: true
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: false
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: false
      description: If the resource is not found, the Server SHOULD return either the 404 Not Found, 410 Gone or 403 Forbidden status without the Upload-Offset header.
      example:
        fault: false
        id: 123abc
        message: parameter 'p' must be an integer
        name: bad_request
        temporary: false
        timeout: false
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
