openapi: 3.0.3
info:
  title: Goa API
  version: "1.0"
servers:
- url: http://localhost:80
  description: Default server for resume
paths:
  /resumes:
    get:
      tags:
      - resume
      summary: list resume
      description: List all stored resumes
      operationId: resume#list
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StoredResumeCollection'
              example:
              - created_at: Ab molestiae et.
                education:
                - institution: Possimus voluptas eum.
                  major: Sint eos.
                - institution: Possimus voluptas eum.
                  major: Sint eos.
                experience:
                - company: Eligendi alias.
                  duration: 894629370113642138
                  role: Ut quia exercitationem autem non nisi.
                - company: Eligendi alias.
                  duration: 894629370113642138
                  role: Ut quia exercitationem autem non nisi.
                - company: Eligendi alias.
                  duration: 894629370113642138
                  role: Ut quia exercitationem autem non nisi.
                - company: Eligendi alias.
                  duration: 894629370113642138
                  role: Ut quia exercitationem autem non nisi.
                id: 6715916505894079249
                name: Possimus autem est.
              - created_at: Ab molestiae et.
                education:
                - institution: Possimus voluptas eum.
                  major: Sint eos.
                - institution: Possimus voluptas eum.
                  major: Sint eos.
                experience:
                - company: Eligendi alias.
                  duration: 894629370113642138
                  role: Ut quia exercitationem autem non nisi.
                - company: Eligendi alias.
                  duration: 894629370113642138
                  role: Ut quia exercitationem autem non nisi.
                - company: Eligendi alias.
                  duration: 894629370113642138
                  role: Ut quia exercitationem autem non nisi.
                - company: Eligendi alias.
                  duration: 894629370113642138
                  role: Ut quia exercitationem autem non nisi.
                id: 6715916505894079249
                name: Possimus autem est.
              - created_at: Ab molestiae et.
                education:
                - institution: Possimus voluptas eum.
                  major: Sint eos.
                - institution: Possimus voluptas eum.
                  major: Sint eos.
                experience:
                - company: Eligendi alias.
                  duration: 894629370113642138
                  role: Ut quia exercitationem autem non nisi.
                - company: Eligendi alias.
                  duration: 894629370113642138
                  role: Ut quia exercitationem autem non nisi.
                - company: Eligendi alias.
                  duration: 894629370113642138
                  role: Ut quia exercitationem autem non nisi.
                - company: Eligendi alias.
                  duration: 894629370113642138
                  role: Ut quia exercitationem autem non nisi.
                id: 6715916505894079249
                name: Possimus autem est.
              - created_at: Ab molestiae et.
                education:
                - institution: Possimus voluptas eum.
                  major: Sint eos.
                - institution: Possimus voluptas eum.
                  major: Sint eos.
                experience:
                - company: Eligendi alias.
                  duration: 894629370113642138
                  role: Ut quia exercitationem autem non nisi.
                - company: Eligendi alias.
                  duration: 894629370113642138
                  role: Ut quia exercitationem autem non nisi.
                - company: Eligendi alias.
                  duration: 894629370113642138
                  role: Ut quia exercitationem autem non nisi.
                - company: Eligendi alias.
                  duration: 894629370113642138
                  role: Ut quia exercitationem autem non nisi.
                id: 6715916505894079249
                name: Possimus autem est.
    post:
      tags:
      - resume
      summary: add resume
      description: Add n number of resumes and return their IDs. This is a multipart
        request and each part has field name 'resume' and contains the encoded resume
        to be added.
      operationId: resume#add
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Resume'
              example:
              - education:
                - institution: Similique libero.
                  major: Facere cum maiores quo at ducimus.
                - institution: Similique libero.
                  major: Facere cum maiores quo at ducimus.
                experience:
                - company: Quia et.
                  duration: 364652394428559071
                  role: In qui dolorum adipisci itaque.
                - company: Quia et.
                  duration: 364652394428559071
                  role: In qui dolorum adipisci itaque.
                - company: Quia et.
                  duration: 364652394428559071
                  role: In qui dolorum adipisci itaque.
                - company: Quia et.
                  duration: 364652394428559071
                  role: In qui dolorum adipisci itaque.
                name: Et aut sint dolor tempore quidem.
              - education:
                - institution: Similique libero.
                  major: Facere cum maiores quo at ducimus.
                - institution: Similique libero.
                  major: Facere cum maiores quo at ducimus.
                experience:
                - company: Quia et.
                  duration: 364652394428559071
                  role: In qui dolorum adipisci itaque.
                - company: Quia et.
                  duration: 364652394428559071
                  role: In qui dolorum adipisci itaque.
                - company: Quia et.
                  duration: 364652394428559071
                  role: In qui dolorum adipisci itaque.
                - company: Quia et.
                  duration: 364652394428559071
                  role: In qui dolorum adipisci itaque.
                name: Et aut sint dolor tempore quidem.
              - education:
                - institution: Similique libero.
                  major: Facere cum maiores quo at ducimus.
                - institution: Similique libero.
                  major: Facere cum maiores quo at ducimus.
                experience:
                - company: Quia et.
                  duration: 364652394428559071
                  role: In qui dolorum adipisci itaque.
                - company: Quia et.
                  duration: 364652394428559071
                  role: In qui dolorum adipisci itaque.
                - company: Quia et.
                  duration: 364652394428559071
                  role: In qui dolorum adipisci itaque.
                - company: Quia et.
                  duration: 364652394428559071
                  role: In qui dolorum adipisci itaque.
                name: Et aut sint dolor tempore quidem.
              - education:
                - institution: Similique libero.
                  major: Facere cum maiores quo at ducimus.
                - institution: Similique libero.
                  major: Facere cum maiores quo at ducimus.
                experience:
                - company: Quia et.
                  duration: 364652394428559071
                  role: In qui dolorum adipisci itaque.
                - company: Quia et.
                  duration: 364652394428559071
                  role: In qui dolorum adipisci itaque.
                - company: Quia et.
                  duration: 364652394428559071
                  role: In qui dolorum adipisci itaque.
                - company: Quia et.
                  duration: 364652394428559071
                  role: In qui dolorum adipisci itaque.
                name: Et aut sint dolor tempore quidem.
            example:
            - education:
              - institution: Similique libero.
                major: Facere cum maiores quo at ducimus.
              - institution: Similique libero.
                major: Facere cum maiores quo at ducimus.
              experience:
              - company: Quia et.
                duration: 364652394428559071
                role: In qui dolorum adipisci itaque.
              - company: Quia et.
                duration: 364652394428559071
                role: In qui dolorum adipisci itaque.
              - company: Quia et.
                duration: 364652394428559071
                role: In qui dolorum adipisci itaque.
              - company: Quia et.
                duration: 364652394428559071
                role: In qui dolorum adipisci itaque.
              name: Et aut sint dolor tempore quidem.
            - education:
              - institution: Similique libero.
                major: Facere cum maiores quo at ducimus.
              - institution: Similique libero.
                major: Facere cum maiores quo at ducimus.
              experience:
              - company: Quia et.
                duration: 364652394428559071
                role: In qui dolorum adipisci itaque.
              - company: Quia et.
                duration: 364652394428559071
                role: In qui dolorum adipisci itaque.
              - company: Quia et.
                duration: 364652394428559071
                role: In qui dolorum adipisci itaque.
              - company: Quia et.
                duration: 364652394428559071
                role: In qui dolorum adipisci itaque.
              name: Et aut sint dolor tempore quidem.
            - education:
              - institution: Similique libero.
                major: Facere cum maiores quo at ducimus.
              - institution: Similique libero.
                major: Facere cum maiores quo at ducimus.
              experience:
              - company: Quia et.
                duration: 364652394428559071
                role: In qui dolorum adipisci itaque.
              - company: Quia et.
                duration: 364652394428559071
                role: In qui dolorum adipisci itaque.
              - company: Quia et.
                duration: 364652394428559071
                role: In qui dolorum adipisci itaque.
              - company: Quia et.
                duration: 364652394428559071
                role: In qui dolorum adipisci itaque.
              name: Et aut sint dolor tempore quidem.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
                  example: 4761814395796103656
                  format: int64
                example:
                - 1492937906920113174
                - 8629193590966258329
                - 9222533118015397217
              example:
              - 769228498760051388
              - 197623837879535554
components:
  schemas:
    Education:
      type: object
      properties:
        institution:
          type: string
          description: Name of the institution
          example: Fugiat et ipsa animi et officiis consectetur.
        major:
          type: string
          description: Major name
          example: Quod sapiente quia laboriosam rerum beatae dicta.
      example:
        institution: Exercitationem non minima.
        major: Officia sapiente cum laboriosam et nesciunt.
      required:
      - institution
      - major
    Experience:
      type: object
      properties:
        company:
          type: string
          description: Name of the company
          example: Necessitatibus officiis similique facilis sapiente.
        duration:
          type: integer
          description: Duration (in years) in the company
          example: 2049499442298109518
          format: int64
        role:
          type: string
          description: Name of the role in the company
          example: Pariatur ut.
      example:
        company: Labore et hic.
        duration: 1245039252925383067
        role: Quis voluptatem ducimus est illum voluptatem voluptatum.
      required:
      - company
      - role
      - duration
    GoaResume:
      type: object
      properties:
        created_at:
          type: string
          description: Time when resume was created
          example: Quae voluptatum ex at doloribus assumenda.
        education:
          type: array
          items:
            $ref: '#/components/schemas/Education'
          description: Education section in the resume
          example:
          - institution: Autem voluptate.
            major: Voluptas distinctio placeat.
          - institution: Autem voluptate.
            major: Voluptas distinctio placeat.
          - institution: Autem voluptate.
            major: Voluptas distinctio placeat.
        experience:
          type: array
          items:
            $ref: '#/components/schemas/Experience'
          description: Experience section in the resume
          example:
          - company: Aut rem.
            duration: 5176619058752078184
            role: Consequuntur quam est commodi cumque eaque quisquam.
          - company: Aut rem.
            duration: 5176619058752078184
            role: Consequuntur quam est commodi cumque eaque quisquam.
          - company: Aut rem.
            duration: 5176619058752078184
            role: Consequuntur quam est commodi cumque eaque quisquam.
        id:
          type: integer
          description: ID of the resume
          example: 4246290979223505482
          format: int64
        name:
          type: string
          description: Name in the resume
          example: Sequi nihil et doloremque quidem fugit delectus.
      example:
        created_at: Non quod voluptatem quasi.
        education:
        - institution: Autem voluptate.
          major: Voluptas distinctio placeat.
        - institution: Autem voluptate.
          major: Voluptas distinctio placeat.
        experience:
        - company: Aut rem.
          duration: 5176619058752078184
          role: Consequuntur quam est commodi cumque eaque quisquam.
        - company: Aut rem.
          duration: 5176619058752078184
          role: Consequuntur quam est commodi cumque eaque quisquam.
        - company: Aut rem.
          duration: 5176619058752078184
          role: Consequuntur quam est commodi cumque eaque quisquam.
        id: 4044863657372003187
        name: Numquam quibusdam mollitia.
      required:
      - id
      - name
      - experience
      - education
      - created_at
    Resume:
      type: object
      properties:
        education:
          type: array
          items:
            $ref: '#/components/schemas/Education'
          description: Education section in the resume
          example:
          - institution: Similique libero.
            major: Facere cum maiores quo at ducimus.
          - institution: Similique libero.
            major: Facere cum maiores quo at ducimus.
        experience:
          type: array
          items:
            $ref: '#/components/schemas/Experience'
          description: Experience section in the resume
          example:
          - company: Quia et.
            duration: 364652394428559071
            role: In qui dolorum adipisci itaque.
          - company: Quia et.
            duration: 364652394428559071
            role: In qui dolorum adipisci itaque.
        name:
          type: string
          description: Name in the resume
          example: Dicta minima.
      example:
        education:
        - institution: Similique libero.
          major: Facere cum maiores quo at ducimus.
        - institution: Similique libero.
          major: Facere cum maiores quo at ducimus.
        - institution: Similique libero.
          major: Facere cum maiores quo at ducimus.
        experience:
        - company: Quia et.
          duration: 364652394428559071
          role: In qui dolorum adipisci itaque.
        - company: Quia et.
          duration: 364652394428559071
          role: In qui dolorum adipisci itaque.
        - company: Quia et.
          duration: 364652394428559071
          role: In qui dolorum adipisci itaque.
        name: Sunt consequatur est quo consequatur aut.
      required:
      - name
    StoredResumeCollection:
      type: array
      items:
        $ref: '#/components/schemas/GoaResume'
      example:
      - created_at: Ab molestiae et.
        education:
        - institution: Possimus voluptas eum.
          major: Sint eos.
        - institution: Possimus voluptas eum.
          major: Sint eos.
        experience:
        - company: Eligendi alias.
          duration: 894629370113642138
          role: Ut quia exercitationem autem non nisi.
        - company: Eligendi alias.
          duration: 894629370113642138
          role: Ut quia exercitationem autem non nisi.
        - company: Eligendi alias.
          duration: 894629370113642138
          role: Ut quia exercitationem autem non nisi.
        - company: Eligendi alias.
          duration: 894629370113642138
          role: Ut quia exercitationem autem non nisi.
        id: 6715916505894079249
        name: Possimus autem est.
      - created_at: Ab molestiae et.
        education:
        - institution: Possimus voluptas eum.
          major: Sint eos.
        - institution: Possimus voluptas eum.
          major: Sint eos.
        experience:
        - company: Eligendi alias.
          duration: 894629370113642138
          role: Ut quia exercitationem autem non nisi.
        - company: Eligendi alias.
          duration: 894629370113642138
          role: Ut quia exercitationem autem non nisi.
        - company: Eligendi alias.
          duration: 894629370113642138
          role: Ut quia exercitationem autem non nisi.
        - company: Eligendi alias.
          duration: 894629370113642138
          role: Ut quia exercitationem autem non nisi.
        id: 6715916505894079249
        name: Possimus autem est.
tags:
- name: resume
  description: The storage service makes it possible to add resumes using multipart.
